### ISSUE TITLE
Errors installing and afterwards

### ISSUE THREAD

**Issue by nomadturk** [rafi/vim-config#19]
Hi,

I had a real old copy of your config and I wanted to upgrade it.
Turns out you changed the whole setup (:

But I'm having troubles with the new version.
First, I cleaned all .vim* and related files in my home and home/.cache folders.
Then I went with your installation steps
I had to replace vim with vim-nox since my repo-downloaded vim didn't have lua or python support in it.

1- Having to use SPACE + ENTER during installation due to "more" command is a drag.

2- Right after installing, even before using vim I have this error on my console:

```
Error detected while processing /root/.vim/config/theme.vim:
line   16:
E185: Cannot find color scheme 'hybrid'
Press ENTER or type command to continue
```

3- Then I tried opening the file to check what's inside and got a brand new error.

```
[10:10] root@odin.golgeli.net: ~/.vim # vim /root/.vim/config/theme.vim
Error detected while processing /root/.cache/vim/dein/.dein/plugin/parenmatch.vim:
line   21:
E216: No such group or event: OptionSet matchpairs call parenmatch#setup()
Press ENTER or type command to continue
```

4- When you click Enter to that message, you're presented with another one:

```
"~/.vim/config/theme.vim" 20L, 392C
[dein] #User#dein#source#unite.vim is deprecated.
[dein] Please use new hook feature instead.
[dein] #User#dein#source#vimfiler.vim is deprecated.
[dein] Please use new hook feature instead.
Press ENTER or type command to continue
```

I did open that file afterwards.
Then I tried another file.

I must admit, it does have a a sleek theme and I liked it. But after a quick glance and compared to your old version, I found out that there's some stuff that's rather disturbing as well.

Autocomplete function does mess with using TAB.
When you double click mouse, it does insert random strings here and there AND it the search function went ballistic on me. Tried searching for whatever I don't know, added error lines in the file I was working on.

Again, with using mouse, I tried to copy some part of the text since I wanted to copy it.
Well, turns out I can't. I started seeing "Invalid register name" errors on the command section. Starting from whatever and continuing with many other error messages  E354, E348 etc.

Furthermore, The bottom left area where you show the name of the file has  an error where it shows the name of 
*config/vimrc* as *confi/vimrc*

![2016-04-29_11-44-22](https://cloud.githubusercontent.com/assets/10355660/14911963/ae44d1f8-0e01-11e6-9dae-8ab198f1da7b.png)

I think you should try a clean install and see all those errors for yourself.
I admit.... Right now it's not of much use to me and the old one seems safer to use.

![odin_-_plesk_-_xshell_5_ free_for_homeschool _2016-04-29_11-57-31](https://cloud.githubusercontent.com/assets/10355660/14911972/c9f3bf36-0e01-11e6-85b5-c4c2c2e5fb1b.png)

**Comment by rafi** [comment]
Hi Omer, thanks for feedback.
I've changed the plugin manager because Shougo discontinued [neobunlde.vim](https://github.com/Shougo/neobundle.vim) development and started working exclusively on [dein.vim](https://github.com/Shougo/dein.vim), which is the most sophisticated plugin manager out there currently.

1. Are you using Vim or Neovim? What OS are you using? Indeed the initial setup is a drag. Hopefully I fixed the "More" issue in Vim.
2. The problem with color-scheme is annoying, I haven't been able to fix it yet. I'll come up with something, but as far as I tested, the 2nd time you run vim, it works without errors. Try running `:call dein#clear_state()` and restart vim to clean dein's state cache.
3. The issue with `itchyny/vim-parenmatch` is weird. You can try disabling it in `config/plugins.vim` and let me know.
4. This makes me feel you're clone of my vim-config isn't up-to-date.
5. Autocomplete - For Neovim, I'm using the new feature-full deoplete.vim](https://github.com/Shougo/deoplete.nvim), and for Vim - [neocomplete.vim](https://github.com/Shougo/neocomplete.vim). I fixed an issue that might have prevented neocomplete to work.
6. Copying text with mouse: This might not be related to Vim at all. What terminal emulator are you using?
7. The bottom area is truncated by design. You can configure how many characters max. to leave there with:
```vim
" Tabs: Maximum number of directories in file path
let g:blk_tab_display_max_dirs = 1
" Tabs: Maximum number of characters in each directory
let g:blk_tab_display_max_dir_chars = 8

" Statusline: Maximum number of directories in file path
let g:blk_filename_max_dirs = 3
" Statusline: Maximum number of characters in each directory
let g:blk_filename_max_dir_chars = 5
```

I've updated configuration and tested with a clean install in vim & neovim.
1. Please delete the `~/.cache/vim/dein` directory, or run `:call dein#clear_state()`
2. Now run `vim +q` or `nvim +q`

I hope this solves all the issues you've experienced.

**Comment by nomadturk** [comment]
Hi @rafi ,

Thanks for the detailed explanation.

First of all yeah, I should've mentioned it.

1- I'm using Debian Jessie but tested it on Ubuntu and Linux Mint as well. Same result.
I'm using plain vim but since it doesn't have Lua, I installed vim-nox package to satisfy the dependency.

2- Will try the command if I can get the newer version to run. The freshly updated installer greets us with a brand new error this time ^^

![odin_-_plesk_-_xshell_5_ free_for_homeschool _2016-05-02_11-20-16](https://cloud.githubusercontent.com/assets/10355660/14950750/ddf4c19e-105c-11e6-90fb-aab74fdce730.png)


Though on one of the boxes I was trying which had the version I tried a few days ago, I didn't have the color scheme error anymore, so yeah maybe opening second time is the charm for that.

**Update**: I re-installed it again. It still didn't work. But on my Ubuntu system it started installing Shougo, pluginsand dein without errors,  Also, I created a new user on my Debian Jessie, I even removed all the /etc/skel files copied there and removed every dotfile but the result was the same. Strange.


3- Since I can't make a fresh install anymore, I can't try fixing the parenmatch error either.

4- Nope, I do have an old copy of your config indeed but that's on another machine. All my tries were done after running the command `rm -rf .cache/vim .vim*`

And this message is persistent. Everytime I open a file to edit with vim, it's popping up before the display of the contents.

5- ...

6- On the terminal front, I'm using XShell5 to connect to my servers. But I doubt it has anything to do with it. But for some reason with your vim-config, I'm unable to select and copy text. With other configs I don't have this trouble.



PS: On the Ubuntu system I managed to install it, it did start without  errors. I didn't have unite.vim and vimfiler.vim related errors either.


I'll tinker more when I have time.

**Comment by rafi** [comment]
Quick questions: 
1. Do you have a root folder `/vim`?
2. Do you have `$XDG_CONFIG_HOME` environment variable set? Try running `echo $XDG_CONFIG_HOME`  to see if there's any output.

**Comment by nomadturk** [comment]
Quick reply:

1- Strange. One of the scripts I was trying mistakenly created a /vim folder I guess. Indeed I had one. I removed that and tried a fresh install. Makes me feel like stupid for not checking. ^^

Now it works. I don't get any --more-- screens either. I installed the plugins.
After the end I did get the hybrid message; as expected, at my next start it was gone.

But I still get this error:
```
Error detected while processing /root/.cache/vim/dein/.dein/plugin/parenmatch.vim:
line   21:
E216: No such group or event: OptionSet matchpairs call parenmatch#setup()
Press ENTER or type command to continue
```

After disabling it at `config/plugins.vim` file that message is gone as well.
Before your last update, I was getting unity.vim and vimfiler.vim errors now they're gone as well.


Can you try double clicking anywhere on screen when a file is open?
And try selecting any word. ^^

**Comment by rafi** [comment]
Great. I'll change [these](https://github.com/rafi/vim-config/blob/master/config/vimrc#L14-L20) lines to relate to current file path possibly..

Regarding the mouse issue, what terminal are you using? Can you try disabling [this](https://github.com/rafi/vim-config/blob/master/config%2Fterminal.vim#L66) line?

**Comment by nomadturk** [comment]
Yep.

Before removing /vim folder I managed a successful install by removing 

> if isdirectory($XDG_CONFIG_HOME.'/vim')
> 	let $VIMPATH=expand('$XDG_CONFIG_HOME/vim')
> 	let $VARPATH=expand('$XDG_CACHE_HOME/vim')
> else


Fixing those might result in a better adaptibility.

As for the mouse issue,disabling that line did help prevent vim losing sanity. 
Also unless I use `:set mouse=v` copy function doesn't work.

**Comment by rafi** [comment]
Weird, that's the first thing being set in [config/general.vim](https://github.com/rafi/vim-config/blob/master/config/general.vim#L5)...

**Comment by nomadturk** [comment]
@rafi ,

Well. `:set mouse=vi` or `:set mouse=r` does work but normal mode prevents copying when I'm remote connected. 

Now I tried it with XShell5 and MobaXterm. XShell doesn't allow it when mode is set to nvi but MobaXterm doesn't care. I'm not sure which one is doing the right thing.

**Comment by rafi** [comment]
Fixed `XDG_CONFIG_HOME` when empty with b8d65440
